config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get "/home/about" => "homes#about", as: "about"
  root to: 'homes#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
        
    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  before_action :is_matching_login_user, only: [:destroy]
  def create
    book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comments_params)
    book_comment.book_id = book.id
    book_comment.save
    redirect_to request.referer
  end

  def destroy
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    redirect_to request.referer
  end

  private
  def book_comments_params
    params.require(:book_comment).permit(:comment)
  end

  def is_matching_login_user
    user = BookComment.find(params[:id]).user
    unless user.id == current_user.id
      redirect_to request.referer
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @user = current_user
    @newbook = Book.new
    @book = @user.books.new(book_params)
    @books = Book.all

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @user = current_user
    @newbook = Book.new
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "You have dele book successfully."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    user = Book.find(params[:id]).user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new
    favorite.book_id = book.id
    favorite.save
    
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @newbook = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-5 mx-auto">
  <% if @book.errors.any? %>
    <div class="col-12 alert alert-danger">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1>Editing Book</h1>

  <%= form_with model: @book do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_field :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Update Book", class: "form_control btn btn-success" %>
    </div>
  <% end %>

  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path() %>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="col-md-12 alert alert-danger">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'users/userInfo', user: @user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Body</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td>
            <% if book.favorited_by?(@user) %>
              <%= link_to book_favorites_path(book.id), method: :delete do %>
                <i class="fas fa-heart" style="color: #ff0000;"></i><%= book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book.id), method: :post do %>
                <i class="fas fa-heart" style="color: #0000ff;"></i><%= book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td>コメント数: <%= book.book_comments.count %></td>
        </tr>
       <% end %>
    </tbody>
  </table>

</div>

app/views/books/show.html.erb
<%= render "users/userInfo", user: @user, book: @newbook %>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>

  <%= flash[:notice] %>

  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br />
            <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= @book.title %></td>
        <td><%= @book.body %></td>

        <% if current_user == @book.user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
          </td>
        <% end %>

        <td>
          <% if @book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(@book.id), method: :delete do %>
              <i class="fas fa-heart" style="color: #ff0000;"></i><%= @book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(@book.id), method: :post do %>
              <i class="fas fa-heart" style="color: #0000ff;"></i><%= @book.favorites.count %>
            <% end %>
          <% end %>
        </td>
        <td>コメント数: <%= @book.book_comments.count %></td>
      </tr>
      <% @book_comments.each do |book_comment| %>
        <tr>
          <td>
            <%= link_to user_path(book_comment.user.id) do %>
              <%= image_tag book_comment.user.get_profile_image(50,50) %><br />
              <%= book_comment.user.name %>
            <% end %>
          </td>
          <td><%= book_comment.comment %></td>
          <td>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(@book.id, book_comment.id), method: :delete, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= form_with model: [@book, @book_comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :comment, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "送信", class: "btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/homes/about.html.erb
<div class="mx-auto">
  <h1>Welcome to
  <i class="fas fa-book" style="color: #000000;"></i><strong>Bookers</strong>!
  </h1>
</div>

app/views/homes/top.html.erb
<div class="mx-auto col-xl-6">
  <h1>welcome to
    <i class="fas fa-book" style="color: #000000;"></i><strong>Bookers</strong>
    !!
  </h1>
  <p>In <i class="fas fa-book" style="color: #000000;"></i><strong>Bookers</strong>,</p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>

  <div class="col-10 mx-auto">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-primary mb-3 btn-block"  %>
    </div>
    <div class="row">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-success mb-3 btn-block"  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class='naver-brand text-white', href="/"><h4 class="my-auto">Bookers</h4></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavMenu" aria-controls="NavMenu" aria-expanded="false" area-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="NavMenu">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: "nav-link text-white" do %>
                    <i class="fas fa-home" style="color: #ffffff;"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-white" do %>
                    <i class="fas fa-users" style="color: #ffffff;"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-white" do %>
                    <i class="fas fa-book-open" style="color: #ffffff;"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-white" do %>
                    <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i>
                    Log out
                  <% end %>
                </li>

              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-white" do %>
                    <i class="fas fa-home" style="color: #ffffff;"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-white" do %>
                    <i class="fas fa-link" style="color: #ffffff;"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-white" do %>
                    <i class="fas fa-user-plus" style="color: #ffffff;"></i>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-white" do %>
                    <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mt-3">

      <% flash.each do |mt, m| %>
        <p><%= m %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-4">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/users/_userInfo.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>

  <table class="table">
      <tbody>
          <tr>
              <th>name</th>
              <th><%= user.name %></th>
          </tr>
          <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
          </tr>
      </tbody>
  </table>

  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block btn_sm" do  %>
        <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">
    New book
  </h2>

  <%= form_with model: book do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-5 mx-auto">
  <% if @user.errors.any? %>
    <div class="col-12 alert alert-danger">
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>User info</h2>
  <%= form_with model: @user do |f| %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autocomplete: @user.name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :profile_image %><br />
      <%= f.file_field :profile_image, accept: "image/*" %>
    </div>
    <div class="form-group">
      <%= f.label :introduction %><br />
      <%= f.text_area :introduction, autocomplete: @user.introduction, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Update User", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'userInfo', user: @user, book: @newbook %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(80,80) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'userInfo', user: @user, book: @newbook %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Body</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book.id), method: :delete do %>
                <i class="fas fa-heart" style="color: #ff0000;"></i><%= book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book.id), method: :post do %>
                <i class="fas fa-heart" style="color: #0000ff;"></i><%= book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td>コメント数: <%= book.book_comments.count %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>